// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: education.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Models
type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_education_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Course) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Class struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CourseId      string                 `protobuf:"bytes,5,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Course        *Course                `protobuf:"bytes,6,opt,name=course,proto3,oneof" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_education_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{1}
}

func (x *Class) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Class) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Class) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Class) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

// Requests
type PostCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCourseRequest) Reset() {
	*x = PostCourseRequest{}
	mi := &file_education_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCourseRequest) ProtoMessage() {}

func (x *PostCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCourseRequest.ProtoReflect.Descriptor instead.
func (*PostCourseRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{2}
}

func (x *PostCourseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_education_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_education_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoursesRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetCoursesRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_education_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourseRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_education_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PostClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostClassRequest) Reset() {
	*x = PostClassRequest{}
	mi := &file_education_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostClassRequest) ProtoMessage() {}

func (x *PostClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostClassRequest.ProtoReflect.Descriptor instead.
func (*PostClassRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{7}
}

func (x *PostClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostClassRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassRequest) Reset() {
	*x = GetClassRequest{}
	mi := &file_education_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassRequest) ProtoMessage() {}

func (x *GetClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassRequest.ProtoReflect.Descriptor instead.
func (*GetClassRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{8}
}

func (x *GetClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetClassesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassesRequest) Reset() {
	*x = GetClassesRequest{}
	mi := &file_education_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassesRequest) ProtoMessage() {}

func (x *GetClassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassesRequest.ProtoReflect.Descriptor instead.
func (*GetClassesRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{9}
}

func (x *GetClassesRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetClassesRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type UpdateClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	CourseId      *string                `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClassRequest) Reset() {
	*x = UpdateClassRequest{}
	mi := &file_education_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassRequest) ProtoMessage() {}

func (x *UpdateClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassRequest.ProtoReflect.Descriptor instead.
func (*UpdateClassRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateClassRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateClassRequest) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

type DeleteClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassRequest) Reset() {
	*x = DeleteClassRequest{}
	mi := &file_education_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassRequest) ProtoMessage() {}

func (x *DeleteClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassRequest) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Responses
type PostCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCourseResponse) Reset() {
	*x = PostCourseResponse{}
	mi := &file_education_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCourseResponse) ProtoMessage() {}

func (x *PostCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCourseResponse.ProtoReflect.Descriptor instead.
func (*PostCourseResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{12}
}

func (x *PostCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_education_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{13}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_education_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{14}
}

func (x *GetCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_education_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type PostClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *Class                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostClassResponse) Reset() {
	*x = PostClassResponse{}
	mi := &file_education_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostClassResponse) ProtoMessage() {}

func (x *PostClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostClassResponse.ProtoReflect.Descriptor instead.
func (*PostClassResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{16}
}

func (x *PostClassResponse) GetClass() *Class {
	if x != nil {
		return x.Class
	}
	return nil
}

type GetClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *Class                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassResponse) Reset() {
	*x = GetClassResponse{}
	mi := &file_education_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassResponse) ProtoMessage() {}

func (x *GetClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassResponse.ProtoReflect.Descriptor instead.
func (*GetClassResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{17}
}

func (x *GetClassResponse) GetClass() *Class {
	if x != nil {
		return x.Class
	}
	return nil
}

type GetClassesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*Class               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassesResponse) Reset() {
	*x = GetClassesResponse{}
	mi := &file_education_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassesResponse) ProtoMessage() {}

func (x *GetClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassesResponse.ProtoReflect.Descriptor instead.
func (*GetClassesResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{18}
}

func (x *GetClassesResponse) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type UpdateClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *Class                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClassResponse) Reset() {
	*x = UpdateClassResponse{}
	mi := &file_education_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassResponse) ProtoMessage() {}

func (x *UpdateClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassResponse.ProtoReflect.Descriptor instead.
func (*UpdateClassResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateClassResponse) GetClass() *Class {
	if x != nil {
		return x.Class
	}
	return nil
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_education_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{20}
}

type DeleteClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassResponse) Reset() {
	*x = DeleteClassResponse{}
	mi := &file_education_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassResponse) ProtoMessage() {}

func (x *DeleteClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_education_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassResponse.ProtoReflect.Descriptor instead.
func (*DeleteClassResponse) Descriptor() ([]byte, []int) {
	return file_education_proto_rawDescGZIP(), []int{21}
}

var File_education_proto protoreflect.FileDescriptor

const file_education_proto_rawDesc = "" +
	"\n" +
	"\x0feducation.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf2\x01\n" +
	"\x05Class\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tcourse_id\x18\x05 \x01(\tR\bcourseId\x12'\n" +
	"\x06course\x18\x06 \x01(\v2\n" +
	".pb.CourseH\x00R\x06course\x88\x01\x01B\t\n" +
	"\a_course\"'\n" +
	"\x11PostCourseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetCoursesRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\"G\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"%\n" +
	"\x13DeleteCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x10PostClassRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"!\n" +
	"\x0fGetClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetClassesRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\"v\n" +
	"\x12UpdateClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tcourse_id\x18\x03 \x01(\tH\x01R\bcourseId\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_course_id\"$\n" +
	"\x12DeleteClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x12PostCourseResponse\x12\"\n" +
	"\x06course\x18\x01 \x01(\v2\n" +
	".pb.CourseR\x06course\"7\n" +
	"\x11GetCourseResponse\x12\"\n" +
	"\x06course\x18\x01 \x01(\v2\n" +
	".pb.CourseR\x06course\":\n" +
	"\x12GetCoursesResponse\x12$\n" +
	"\acourses\x18\x01 \x03(\v2\n" +
	".pb.CourseR\acourses\":\n" +
	"\x14UpdateCourseResponse\x12\"\n" +
	"\x06course\x18\x01 \x01(\v2\n" +
	".pb.CourseR\x06course\"4\n" +
	"\x11PostClassResponse\x12\x1f\n" +
	"\x05class\x18\x01 \x01(\v2\t.pb.ClassR\x05class\"3\n" +
	"\x10GetClassResponse\x12\x1f\n" +
	"\x05class\x18\x01 \x01(\v2\t.pb.ClassR\x05class\"9\n" +
	"\x12GetClassesResponse\x12#\n" +
	"\aclasses\x18\x01 \x03(\v2\t.pb.ClassR\aclasses\"6\n" +
	"\x13UpdateClassResponse\x12\x1f\n" +
	"\x05class\x18\x01 \x01(\v2\t.pb.ClassR\x05class\"\x16\n" +
	"\x14DeleteCourseResponse\"\x15\n" +
	"\x13DeleteClassResponse2\xfa\x05\n" +
	"\x10EducationService\x12;\n" +
	"\n" +
	"PostCourse\x12\x15.pb.PostCourseRequest\x1a\x16.pb.PostCourseResponse\x128\n" +
	"\tGetCourse\x12\x14.pb.GetCourseRequest\x1a\x15.pb.GetCourseResponse\x12;\n" +
	"\n" +
	"GetCourses\x12\x15.pb.GetCoursesRequest\x1a\x16.pb.GetCoursesResponse\x12A\n" +
	"\fUpdateCourse\x12\x17.pb.UpdateCourseRequest\x1a\x18.pb.UpdateCourseResponse\x12A\n" +
	"\fDeleteCourse\x12\x17.pb.DeleteCourseRequest\x1a\x18.pb.DeleteCourseResponse\x12>\n" +
	"\vLiveCourses\x12\x15.pb.GetCoursesRequest\x1a\x16.pb.GetCoursesResponse0\x01\x128\n" +
	"\tPostClass\x12\x14.pb.PostClassRequest\x1a\x15.pb.PostClassResponse\x125\n" +
	"\bGetClass\x12\x13.pb.GetClassRequest\x1a\x14.pb.GetClassResponse\x12;\n" +
	"\n" +
	"GetClasses\x12\x15.pb.GetClassesRequest\x1a\x16.pb.GetClassesResponse\x12>\n" +
	"\vUpdateClass\x12\x16.pb.UpdateClassRequest\x1a\x17.pb.UpdateClassResponse\x12>\n" +
	"\vDeleteClass\x12\x16.pb.DeleteClassRequest\x1a\x17.pb.DeleteClassResponse\x12>\n" +
	"\vLiveClasses\x12\x15.pb.GetClassesRequest\x1a\x16.pb.GetClassesResponse0\x01B8Z6github.com/jochem11/inventory-system-back/education/pbb\x06proto3"

var (
	file_education_proto_rawDescOnce sync.Once
	file_education_proto_rawDescData []byte
)

func file_education_proto_rawDescGZIP() []byte {
	file_education_proto_rawDescOnce.Do(func() {
		file_education_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)))
	})
	return file_education_proto_rawDescData
}

var file_education_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_education_proto_goTypes = []any{
	(*Course)(nil),                // 0: pb.Course
	(*Class)(nil),                 // 1: pb.Class
	(*PostCourseRequest)(nil),     // 2: pb.PostCourseRequest
	(*GetCourseRequest)(nil),      // 3: pb.GetCourseRequest
	(*GetCoursesRequest)(nil),     // 4: pb.GetCoursesRequest
	(*UpdateCourseRequest)(nil),   // 5: pb.UpdateCourseRequest
	(*DeleteCourseRequest)(nil),   // 6: pb.DeleteCourseRequest
	(*PostClassRequest)(nil),      // 7: pb.PostClassRequest
	(*GetClassRequest)(nil),       // 8: pb.GetClassRequest
	(*GetClassesRequest)(nil),     // 9: pb.GetClassesRequest
	(*UpdateClassRequest)(nil),    // 10: pb.UpdateClassRequest
	(*DeleteClassRequest)(nil),    // 11: pb.DeleteClassRequest
	(*PostCourseResponse)(nil),    // 12: pb.PostCourseResponse
	(*GetCourseResponse)(nil),     // 13: pb.GetCourseResponse
	(*GetCoursesResponse)(nil),    // 14: pb.GetCoursesResponse
	(*UpdateCourseResponse)(nil),  // 15: pb.UpdateCourseResponse
	(*PostClassResponse)(nil),     // 16: pb.PostClassResponse
	(*GetClassResponse)(nil),      // 17: pb.GetClassResponse
	(*GetClassesResponse)(nil),    // 18: pb.GetClassesResponse
	(*UpdateClassResponse)(nil),   // 19: pb.UpdateClassResponse
	(*DeleteCourseResponse)(nil),  // 20: pb.DeleteCourseResponse
	(*DeleteClassResponse)(nil),   // 21: pb.DeleteClassResponse
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_education_proto_depIdxs = []int32{
	22, // 0: pb.Course.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: pb.Course.updated_at:type_name -> google.protobuf.Timestamp
	22, // 2: pb.Class.created_at:type_name -> google.protobuf.Timestamp
	22, // 3: pb.Class.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: pb.Class.course:type_name -> pb.Course
	0,  // 5: pb.PostCourseResponse.course:type_name -> pb.Course
	0,  // 6: pb.GetCourseResponse.course:type_name -> pb.Course
	0,  // 7: pb.GetCoursesResponse.courses:type_name -> pb.Course
	0,  // 8: pb.UpdateCourseResponse.course:type_name -> pb.Course
	1,  // 9: pb.PostClassResponse.class:type_name -> pb.Class
	1,  // 10: pb.GetClassResponse.class:type_name -> pb.Class
	1,  // 11: pb.GetClassesResponse.classes:type_name -> pb.Class
	1,  // 12: pb.UpdateClassResponse.class:type_name -> pb.Class
	2,  // 13: pb.EducationService.PostCourse:input_type -> pb.PostCourseRequest
	3,  // 14: pb.EducationService.GetCourse:input_type -> pb.GetCourseRequest
	4,  // 15: pb.EducationService.GetCourses:input_type -> pb.GetCoursesRequest
	5,  // 16: pb.EducationService.UpdateCourse:input_type -> pb.UpdateCourseRequest
	6,  // 17: pb.EducationService.DeleteCourse:input_type -> pb.DeleteCourseRequest
	4,  // 18: pb.EducationService.LiveCourses:input_type -> pb.GetCoursesRequest
	7,  // 19: pb.EducationService.PostClass:input_type -> pb.PostClassRequest
	8,  // 20: pb.EducationService.GetClass:input_type -> pb.GetClassRequest
	9,  // 21: pb.EducationService.GetClasses:input_type -> pb.GetClassesRequest
	10, // 22: pb.EducationService.UpdateClass:input_type -> pb.UpdateClassRequest
	11, // 23: pb.EducationService.DeleteClass:input_type -> pb.DeleteClassRequest
	9,  // 24: pb.EducationService.LiveClasses:input_type -> pb.GetClassesRequest
	12, // 25: pb.EducationService.PostCourse:output_type -> pb.PostCourseResponse
	13, // 26: pb.EducationService.GetCourse:output_type -> pb.GetCourseResponse
	14, // 27: pb.EducationService.GetCourses:output_type -> pb.GetCoursesResponse
	15, // 28: pb.EducationService.UpdateCourse:output_type -> pb.UpdateCourseResponse
	20, // 29: pb.EducationService.DeleteCourse:output_type -> pb.DeleteCourseResponse
	14, // 30: pb.EducationService.LiveCourses:output_type -> pb.GetCoursesResponse
	16, // 31: pb.EducationService.PostClass:output_type -> pb.PostClassResponse
	17, // 32: pb.EducationService.GetClass:output_type -> pb.GetClassResponse
	18, // 33: pb.EducationService.GetClasses:output_type -> pb.GetClassesResponse
	19, // 34: pb.EducationService.UpdateClass:output_type -> pb.UpdateClassResponse
	21, // 35: pb.EducationService.DeleteClass:output_type -> pb.DeleteClassResponse
	18, // 36: pb.EducationService.LiveClasses:output_type -> pb.GetClassesResponse
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_education_proto_init() }
func file_education_proto_init() {
	if File_education_proto != nil {
		return
	}
	file_education_proto_msgTypes[1].OneofWrappers = []any{}
	file_education_proto_msgTypes[5].OneofWrappers = []any{}
	file_education_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_education_proto_rawDesc), len(file_education_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_education_proto_goTypes,
		DependencyIndexes: file_education_proto_depIdxs,
		MessageInfos:      file_education_proto_msgTypes,
	}.Build()
	File_education_proto = out.File
	file_education_proto_goTypes = nil
	file_education_proto_depIdxs = nil
}
