version: "3.7"

services:

  education:
    build:
      context: .
      dockerfile: ./education/app.dockerfile
    depends_on:
      - education_db
    environment:
      DATABASE_URL: postgres://postgres:jochie@education_db/inventory-system-back?sslmode=disable
    restart: on-failure

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - education
    environment:
      EDUCATION_SERVICE_URL: education:8080
    restart: on-failure

  education_db:
    build:
      context: ./education
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: inventory-system-back
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "jochie"
    ports:
      - "5433:5432"
    restart: unless-stopped